// Single definition of the "New entry" submission form. Used to:
//  - generate .github/ISSUE_TEMPLATE/new-entry.yml (scripts/sync.mjs)
//  - parse submitted issue bodies into entry JSON (scripts/issue-to-entry.mjs)
//  - publish a plain-markdown issue body template for API-only agents (/contribute.json)
// GitHub renders issue-form answers as "### <label>\n\n<value>", so labels are the parse keys:
// never rename a label without regenerating the form (node scripts/sync.mjs).
import { loadCategories } from './categories.mjs';

const ENUMS = {
  pricing: ['free', 'freemium', 'paid', 'open-source', 'unknown'],
  status: ['active', 'beta', 'deprecated', 'unknown'],
  auth: ['none', 'api-key', 'oauth', 'other'],
};

export function formFields() {
  const cats = loadCategories();
  return [
    { key: 'id', label: 'Entry id', type: 'input', required: true, description: 'Kebab-case slug, unique across the directory; becomes the filename content/<category>/<id>.json.', placeholder: 'my-tool' },
    { key: 'name', label: 'Name', type: 'input', required: true, description: 'Display name (max 120 chars).', placeholder: 'My Tool' },
    { key: 'category', label: 'Category', type: 'dropdown', required: true, description: cats.map((c) => `${c.slug}: ${c.description}`).join(' | '), options: cats.map((c) => c.slug) },
    { key: 'summary', label: 'Summary', type: 'input', required: true, description: 'One neutral line, 10-200 characters, plain text (no marketing copy).', placeholder: 'What it does for agents, in one line.' },
    { key: 'url', label: 'Homepage URL', type: 'input', required: true, description: 'Canonical homepage, https://...', placeholder: 'https://example.com' },
    { key: 'repo', label: 'Repository URL', type: 'input', description: 'Source repository, if any.', placeholder: 'https://github.com/owner/repo' },
    { key: 'docs', label: 'Docs URL', type: 'input', description: 'Documentation URL, if any.', placeholder: 'https://example.com/docs' },
    { key: 'description', label: 'Description', type: 'textarea', description: 'Optional longer description in markdown.' },
    { key: 'tags', label: 'Tags', type: 'input', list: 'comma', description: 'Comma-separated kebab-case tags (max 20).', placeholder: 'web-search, mcp, python' },
    { key: 'license', label: 'License', type: 'input', description: 'SPDX identifier where possible (MIT, Apache-2.0) or "proprietary".', placeholder: 'MIT' },
    { key: 'pricing', label: 'Pricing', type: 'dropdown', options: ENUMS.pricing, description: 'Leave empty if unknown.' },
    { key: 'status', label: 'Status', type: 'dropdown', options: ENUMS.status, description: 'Leave empty if unknown.' },
    { key: 'agent_access.llms_txt', label: 'llms.txt URL', type: 'input', description: 'URL of the resource\'s llms.txt, if it has one.', placeholder: 'https://example.com/llms.txt' },
    { key: 'agent_access.openapi', label: 'OpenAPI URL', type: 'input', description: 'URL of an OpenAPI spec, if any.', placeholder: 'https://example.com/openapi.json' },
    { key: 'agent_access.mcp_endpoint', label: 'MCP endpoint', type: 'input', description: 'Remote MCP endpoint (http/https/ws/wss), if any.', placeholder: 'https://example.com/mcp' },
    { key: 'agent_access.auth', label: 'Auth', type: 'dropdown', options: ENUMS.auth, description: 'How agents authenticate. Leave empty if not applicable.' },
    { key: 'agent_access.notes', label: 'Agent access notes', type: 'textarea', description: 'Anything an agent needs to know to use it (max 1000 chars).' },
    { key: 'related', label: 'Related entry ids', type: 'input', list: 'comma', description: 'Comma-separated ids of existing entries (see https://indexagentica.com/api/index.json).', placeholder: 'model-context-protocol' },
    { key: 'sources', label: 'Sources', type: 'textarea', list: 'lines', required: true, description: 'One URL per line that verifies the facts above.', placeholder: 'https://example.com\nhttps://github.com/owner/repo' },
    { key: 'maintainer', label: 'Maintainer', type: 'input', description: 'Who maintains the listed resource, if known.' },
    { key: 'submitted_by', label: 'Submitted by', type: 'input', description: 'Who is submitting: e.g. "ExampleAgent (agent) for @username" or "github:username".', placeholder: 'ExampleAgent (agent) for @username' },
  ];
}

const q = (s) => JSON.stringify(String(s)); // JSON strings are valid YAML double-quoted scalars

export function renderNewEntryForm() {
  const L = [
    '# GENERATED by scripts/sync.mjs from scripts/lib/forms.mjs and schema/categories.json. Do not edit by hand.',
    'name: New entry',
    'description: Submit a new resource for the Index Agentica directory (agents welcome).',
    'title: "[New entry]: "',
    'labels: ["submission", "new-entry"]',
    'body:',
    '  - type: markdown',
    '    attributes:',
    '      value: ' + q('Fields map 1:1 to the [entry schema](https://indexagentica.com/schema/). A maintainer reviews the submission; adding the `approved` label opens a pull request automatically. Prefer a direct PR? See https://indexagentica.com/agents/#contribute'),
  ];
  for (const f of formFields()) {
    L.push(`  - type: ${f.type}`, `    id: ${f.key.replace(/\./g, '_')}`, '    attributes:', `      label: ${q(f.label)}`);
    if (f.description) L.push(`      description: ${q(f.description)}`);
    if (f.placeholder) L.push(`      placeholder: ${q(f.placeholder)}`);
    if (f.options) { L.push('      options:'); f.options.forEach((o) => L.push(`        - ${q(o)}`)); }
    L.push('    validations:', `      required: ${!!f.required}`);
  }
  L.push(
    '  - type: checkboxes',
    '    id: confirm',
    '    attributes:',
    '      label: Confirmation',
    '      options:',
    `        - label: ${q('The facts above are verifiable from the listed sources, and any affiliation with the resource is disclosed in the description or notes.')}`,
    '          required: true',
  );
  return L.join('\n') + '\n';
}

// Markdown body equivalent to what the form produces: for agents that create issues via the API.
export function issueBodyTemplate() {
  return formFields().map((f) => `### ${f.label}\n\n${f.required ? `<${f.key}>` : '_No response_'}`).join('\n\n') + '\n';
}

// Parse an issue-form body into { entry, problems }. Does not validate against the schema.
export function parseIssueBody(body) {
  // Only headings that match a known form label start a section, so "###" inside a
  // markdown description doesn't break parsing.
  const known = new Set([...formFields().map((f) => f.label.toLowerCase()), 'confirmation']);
  const sections = {};
  let current = null;
  for (const line of String(body || '').replace(/\r\n?/g, '\n').split('\n')) {
    const m = line.match(/^###[ \t]+(.+?)\s*$/);
    if (m && known.has(m[1].toLowerCase())) { current = m[1].toLowerCase(); sections[current] = []; continue; }
    if (current) sections[current].push(line);
  }
  for (const k of Object.keys(sections)) {
    let value = sections[k].join('\n').trim();
    if (value === '_No response_' || value === 'None') value = '';
    sections[k] = value;
  }
  const entry = {};
  const problems = [];
  for (const f of formFields()) {
    let v = sections[f.label.toLowerCase()];
    if (v === undefined) { if (f.required) problems.push(`Missing section "### ${f.label}"`); continue; }
    if (f.type === 'input') v = v.replace(/^`+|`+$/g, '').trim();
    if (!v) { if (f.required) problems.push(`"${f.label}" is required`); continue; }
    if (f.list === 'comma') v = v.split(/[,\n]/).map((s) => s.trim()).filter(Boolean);
    if (f.list === 'lines') v = v.split('\n').map((s) => s.replace(/^\s*(?:[-*+]|\d+\.)\s+/, '').replace(/^<|>$/g, '').trim()).filter(Boolean);
    if (f.key === 'tags') v = v.map((t) => t.toLowerCase().replace(/\s+/g, '-'));
    const [a, b] = f.key.split('.');
    if (b) (entry[a] ||= {})[b] = v;
    else entry[a] = v;
  }
  return { entry, problems };
}
