#!/usr/bin/env node
// Propagate schema/categories.json (and the form definition) to generated files:
//   schema/entry.schema.json  (properties.category.enum)
//   .github/ISSUE_TEMPLATE/new-entry.yml
//   content/README.md         (categories table between markers)
//   content/<category>/       (folders, with .gitkeep)
// Usage: node scripts/sync.mjs          write changes
//        node scripts/sync.mjs --check  exit 1 if anything is out of date (used by validate.mjs)
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, SCHEMA_PATH, loadCategories } from './lib/categories.mjs';
import { renderNewEntryForm } from './lib/forms.mjs';

export const FORM_PATH = path.join(ROOT, '.github/ISSUE_TEMPLATE/new-entry.yml');
export const CONTENT_README = path.join(ROOT, 'content/README.md');
const START = '<!-- categories:start (generated by scripts/sync.mjs from schema/categories.json) -->';
const END = '<!-- categories:end -->';

export function expectedFiles() {
  const cats = loadCategories();
  const schemaText = fs.readFileSync(SCHEMA_PATH, 'utf8');
  const schema = JSON.parse(schemaText);
  schema.properties.category.enum = cats.map((c) => c.slug);
  const readme = fs.readFileSync(CONTENT_README, 'utf8');
  const table = ['| slug | what goes here |', '|---|---|', ...cats.map((c) => `| \`${c.slug}\` | ${c.description} |`)].join('\n');
  let newReadme = readme;
  if (readme.includes(START) && readme.includes(END)) newReadme = readme.slice(0, readme.indexOf(START) + START.length) + '\n' + table + '\n' + readme.slice(readme.indexOf(END));
  return [
    [SCHEMA_PATH, JSON.stringify(schema, null, 2) + '\n'],
    [FORM_PATH, renderNewEntryForm()],
    [CONTENT_README, newReadme],
  ];
}

export function checkSync() {
  const problems = [];
  for (const [file, want] of expectedFiles()) {
    const have = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    const rel = path.relative(ROOT, file);
    if (file === SCHEMA_PATH) {
      const enumHave = JSON.parse(have).properties.category.enum;
      const enumWant = JSON.parse(want).properties.category.enum;
      if (JSON.stringify(enumHave) !== JSON.stringify(enumWant)) problems.push({ file: rel, message: `category enum [${enumHave.join(', ')}] does not match schema/categories.json [${enumWant.join(', ')}]`, hint: 'Edit schema/categories.json (slug, name, description), then run: node scripts/sync.mjs' });
    } else if (have !== want) problems.push({ file: rel, message: 'generated content is out of date', hint: 'Run: node scripts/sync.mjs' });
  }
  for (const c of loadCategories()) if (!fs.existsSync(path.join(ROOT, 'content', c.slug))) problems.push({ file: `content/${c.slug}/`, message: 'category folder is missing', hint: 'Run: node scripts/sync.mjs' });
  return problems;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  if (process.argv.includes('--check')) {
    const p = checkSync();
    p.forEach((x) => console.error(`✗ ${x.file}: ${x.message}\n    fix: ${x.hint}`));
    if (p.length) process.exit(1);
    console.log('✓ generated files are in sync with schema/categories.json');
  } else {
    for (const [file, want] of expectedFiles()) {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      const have = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
      if (have !== want) { fs.writeFileSync(file, want); console.log(`updated ${path.relative(ROOT, file)}`); }
    }
    for (const c of loadCategories()) {
      const d = path.join(ROOT, 'content', c.slug);
      if (!fs.existsSync(d)) { fs.mkdirSync(d, { recursive: true }); fs.writeFileSync(path.join(d, '.gitkeep'), ''); console.log(`created content/${c.slug}/`); }
    }
    console.log('sync done');
  }
}
